
---
- name: Create AWS infrastructure for Ansilbe learning
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: present
    region: eu-west-1
    cidr_block_vpc: 172.16.2.0/23
    vpc_name: VPC for Ansible learning
    cidr_block_public: 172.16.2.0/24
    security_group_name: SG
    vpc_id_public: public_subnet
    instance_type: t2.micro
    ami_centos8: ami-0e0669c0b39d3a79f
    key_name: ansible
    private_ip_master: 172.16.2.10
    private_ip_nodes:
      - 172.16.2.21
      - 172.16.2.22
      - 172.16.2.23

  tasks:
    - name: Create VPC 
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_block_vpc }}"
        region: "{{ region }}"
        state: "{{ state }}"
      register: v
    - name: set vpc id to var
      set_fact: 
        vpc_id: "{{ v.vpc.id }}"
    - name: Debug vpc
      debug:       
        var: vpc_id
        verbosity: 4
    - name: Create public subnet
      ec2_vpc_subnet:
        cidr: "{{ cidr_block_public }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: "{{ state }}"
      register: ps
    - name: Create security group for VPC
      ec2_group:
        region: "{{ region }}"
        state: "{{ state }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ security_group_name }}"
        description: "Security group for VPC"
      register: sg
    - name: Create EC2 master node
      ec2: 
        state: "{{ state }}"
        group_id: "{{ sg.group_id }}"
        image: "{{ ami_centos8 }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ ps.subnet.id }}"
        private_ip: "{{ private_ip_master }}"
    - name: Create EC2 slave nodes
      ec2: 
        state: "{{ state }}"
        group_id: "{{ sg.group_id }}"
        image: "{{ ami_centos8 }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ ps.subnet.id }}"
        private_ip: "{{ item }}"
      loop: "{{ private_ip_nodes }}"
