
---
- name: Create AWS infrastructure for Ansilbe learning
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: present
    region: eu_west-1
    cidr_block_vpc: 172.16.2.0/23
    vpc_name: VPC for Ansible learning
    cidr_block_public: 172.16.2.0/24
    security_group_id: SG
    vpc_id_public: public_subnet
    instance_type: t2.micro
    ami_centos8: ami-0e0669c0b39d3a79f
    key_name: ansible
    private_ip_master: 192.168.2.10
    private_ip_nodes:
      - 192.168.2.21
      - 192.168.2.22
      - 192.168.2.23

  tasks:
    - name: Create VPC 
      amazon.aws.ec2_vpc_net:
        name: {{ vpc_name }}
        cidr_block: {{ cidr_block_vpc }}
        region: {{ region }}
        state: {{ state }}
    - name: Create public subnet
      amazon.aws.ec2_vpc_subnet:
        cidr: {{ cidr_block_public }}
        region: {{ region }}
        vpc_id: {{ vpc_id_public }}
        state: {{ state }}
    - name: Create security group for VPC
      amazon.aws.ec2_group:
        group_id: {{ security_group_id }}
        region: {{ region }}
        state: {{ state }}
        vpc_id: {{ vpc_name }}
    - name: Create EC2 master node
      amazon.aws.ec2: 
        state: {{ state }}
        group_id: {{ security_group_id }}
        image: {{ ami_centos8 }}
        instance_type: {{ instance_type }}
        key_name: {{ key_name }}
        region: {{ region }}
        vpc_subnet_id: {{ vpc_id_public }}
        private_ip: {{ private_ip_master }}
    - name: Create EC2 master node
      amazon.aws.ec2: 
        state: {{ state }}
        group_id: {{ security_group_id }}
        image: {{ ami_centos8 }}
        instance_type: {{ instance_type }}
        key_name: {{ key_name }}
        region: {{ region }}
        vpc_subnet_id: {{ vpc_id_public }}
        private_ip: {{ item }}
      loop: {{ private_ip_nodes }}        