
---
- name: Create AWS infrastructure for Ansilbe learning
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: present
    region: eu-west-1
    cidr_block_vpc: 172.16.2.0/23
    vpc_name: VPC for Ansible learning
    cidr_block_public: 172.16.2.0/24
    security_group_name: SG
    vpc_id_public: public_subnet
    instance_type: t2.micro
    ami_centos8: ami-0e0669c0b39d3a79f
    key_name: ansible
    master_key: ubuntu
    home_net_ip: 77.222.118.226/32
    private_ip_master: 172.16.2.101
    private_ip_nodes:
      - 172.16.2.21
      - 172.16.2.22

  tasks:
    - name: Create VPC 
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_block_vpc }}"
        region: "{{ region }}"
        state: "{{ state }}"
      register: v
    - name: set vpc id to var
      set_fact: 
        vpc_id: "{{ v.vpc.id }}"
    - name: Debug vpc
      debug:       
        var: vpc_id       
    - name: Create public subnet
      ec2_vpc_subnet:
        cidr: "{{ cidr_block_public }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: "{{ state }}"
        map_public: yes
      register: ps
    - name: Create security group for VPC
      ec2_group:
        region: "{{ region }}"
        state: "{{ state }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ security_group_name }}"
        description: "Security group for VPC"
        rules:
          - proto: tcp
            to_port: 80
            from_port: 80
            cidr_ip: "{{ home_net_ip }}"
            rule_desc: "Allow test Apache2 from home ip"
          - proto: tcp
            to_port: 22
            from_port: 22
            cidr_ip: "{{ home_net_ip }}"
            rule_desc: "Allow SSH from home ip"
          - proto: all
            from_port: -1
            to_port: -1
            group_name: "{{ security_group_name }}"
      register: sg
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"  
        tags:
            Name: "IGW for ansible VPC"
      register: igw
    - name: Create Route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        subnets: 
          - "{{ ps.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
    - name: Create EC2 master node
      ec2: 
        state: "{{ state }}"
        group_id: "{{ sg.group_id }}"
        image: "{{ ami_centos8 }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ master_key }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ ps.subnet.id }}"
        private_ip: "{{ private_ip_master }}"
        instance_tags:
          Name: Ansible master
          target: ansible
    - name: Create EC2 slave nodes
      ec2: 
        state: "{{ state }}"
        group_id: "{{ sg.group_id }}"
        image: "{{ ami_centos8 }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ ps.subnet.id }}"
        instance_tags:
          Name: "{{ item }}"
          target: ansible
        private_ip: "{{ item }}"        
      loop: "{{ private_ip_nodes }}"
