---
# tasks file for FTP_role
- name: Install vsftpd
  yum:
    state: latest
    name: vsftpd
  become: true
  notify: 
    - start vsftpd
  
- name: create ftp directories
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:        
    - { path: "{{ pub_dir }}", mode: "0755" }
    - { path: "{{ pub_dir_upload }}", mode: "0777"}
      
- name: install firewalld packet to open port on firewall
  yum:
    state: latest
    name: firewalld
  become: yes

- name: Open port 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  become: yes
  loop:
    - "20-21/tcp"
    - " {{pasv_min_port}}-{{pasv_max_port}}/tcp " 
  notify:
    - reload firewall

- name: Create config file from template
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    mode: 644
    backup: yes
  notify:
    - restart vsftpd

- name: Configure SElinux to allow anonimus ftp
  seboolean:
    name: "{{item}}"
    state: yes
    persistent: yes
  with_items:
    - ftpd_anon_write
    - allow_ftpd_anon_write
  become: true

- name: SELinux add config
  community.general.sefcontext:
    target: "{{ pub_dir_upload }}"
    setype: public_content_rw_t 
    state: present
  become: true

- name: Change SE context by comand
  command: chcon -t public_content_rw_t "{{ pub_dir_upload }}"
  become: true
