---
- name: Playbook3 - modify GRUB config 
  hosts: nodes
 
  tasks:
  - name: Insert net.ifnames=0 в /etc/default/grub
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.iframes)\"[^\"]+)(\".*)'
      line: '\1 net.iframes=0\2'
    become: yes
  - name: Insert biosdevname=0 в /etc/default/grub
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
    become: yes
  - name: Configure GRUB
    raw: grub2-mkconfig -o /boot/grub2/grub.cfg
    become: yes
    