---
- name: Task 2 - create users 
  hosts: nodes
  
  vars:
    users: 
      alice: 
        name: alice1
        pass: verybestpassword
      bob:
        name: bob1
        pass: bobpass
      carol:
        name: carol1
        pass: carolpass
  
  tasks:
    - name: print user names
      debug:
        msg: "Create account for {{ item.key }} username is {{ item.value.name }} email is {{ item.value.name }}.example.com homedir is /home/{{ item.value.name }} pass is {{ item.value.pass }} "
      loop: "{{ lookup('dict', users) }}"
      